# Generated by Django 4.0 on 2021-12-24 10:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0009_remove_requests_user_requests_requester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='requesters',
            field=models.ManyToManyField(blank=True, related_name='requesters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Requests',
        ),
    ]
